display_name: FRB Demo
package_name: frb-demo
icon: assets/icon.png
keywords:
  - flutter
  - rust
  - demo
categories:
  - Utility
generic_name: Demo Application
startup_notify: true
include:
  - build/linux/x64/release/bundle
exclude:
  - "**/.git"
  - "**/node_modules"
