name: Simple Multi-Platform Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config.outputs.FLUTTER_CHANNEL }}
        cache: true
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev
    
    - name: Install Flutter dependencies
      run: flutter pub get
    
    - name: Install Flutter Distributor
      run: dart pub global activate flutter_distributor
    
    - name: Build Linux packages with FastForge
      run: |
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        flutter_distributor package --platform linux --targets deb,appimage --skip-clean
    
    - name: Upload Linux DEB package
      uses: actions/upload-artifact@v4
      with:
        name: linux-deb-package
        path: dist/**/*linux.deb
    
    - name: Upload Linux AppImage package
      uses: actions/upload-artifact@v4
      with:
        name: linux-appimage-package
        path: dist/**/*linux.AppImage

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config.outputs.FLUTTER_CHANNEL }}
        cache: true
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust
    
    - name: Install Flutter dependencies
      run: flutter pub get
    
    - name: Install Flutter Distributor
      run: dart pub global activate flutter_distributor
    
    - name: Build Windows packages with FastForge
      run: |
        $env:PATH += ";$env:USERPROFILE\.pub-cache\bin"
        flutter_distributor package --platform windows --targets exe --skip-clean
    
    - name: Upload Windows EXE package
      uses: actions/upload-artifact@v4
      with:
        name: windows-exe-package
        path: dist/**/*windows.exe

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    
    strategy:
      matrix:
        arch: [x64, arm64]
        include:
          - arch: x64
            target: x86_64-apple-darwin
            suffix: x64
          - arch: arm64
            target: aarch64-apple-darwin
            suffix: arm64
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup FVM
      uses: kuhnroyal/flutter-fvm-config-action@v2
      id: fvm-config
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.fvm-config.outputs.FLUTTER_VERSION }}
        channel: ${{ steps.fvm-config.outputs.FLUTTER_CHANNEL }}
        cache: true
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}
    
    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: rust
    
    - name: Install Flutter dependencies
      run: flutter pub get
    
    - name: Install Flutter Distributor
      run: dart pub global activate flutter_distributor
    
    - name: Build macOS packages with FastForge
      run: |
        export PATH="$PATH":"$HOME/.pub-cache/bin"
        flutter_distributor package --platform macos --targets dmg --skip-clean
    
    - name: Upload macOS DMG package
      uses: actions/upload-artifact@v4
      with:
        name: macos-${{ matrix.suffix }}-dmg-package
        path: dist/**/*macos.dmg

  create-release:
    name: Create Release
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Download Linux DEB package
      uses: actions/download-artifact@v4
      with:
        name: linux-deb-package
        path: ./releases
    
    - name: Download Linux AppImage package
      uses: actions/download-artifact@v4
      with:
        name: linux-appimage-package
        path: ./releases
    
    - name: Download Windows EXE package
      uses: actions/download-artifact@v4
      with:
        name: windows-exe-package
        path: ./releases
    
    - name: Download macOS x64 DMG package
      uses: actions/download-artifact@v4
      with:
        name: macos-x64-dmg-package
        path: ./releases
    
    - name: Download macOS arm64 DMG package
      uses: actions/download-artifact@v4
      with:
        name: macos-arm64-dmg-package
        path: ./releases
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          releases/*
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
